### ISSUE TITLE
[Feat]: 自动删除合并后的 PR 的分支

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Sitemap_Creator#19]
### 选择一个类别

新功能

### 对新功能/建议的描述

在仓库维护者合并更新 PR 后，将对应的分支删除。

### 为什么需要实现此功能

避免仓库出现多个已合并的分支

### 对于实施该功能的方法的建议

我的想法是间接实现这一点，我们现在已经实现了自动关闭过时的 PR，我们可以在那里添加检查已合并但未删除分支的 PR，然后清理它们的分支。

如果需要在合并后立即清理，我认为当前没有办法实现，除非仓库维护者写一个通过 PR 合并触发的工作流。

所以，我们需要将清理分支的操作放在清理 PR 前才能实现当 PR 合并触发我们时可以自动清理。

这是我的预期

```yaml
name: 生成 Sitemap

on:
  push:
    branches:
      - main
      # 当 main 分支上有新推送且以下文件被更改时
    paths:
      - '**/*.html'
      - '**/*.md'
  workflow_dispatch: # 手动运行
  pull_request:
    branches:
      - main
    paths:
      - 'docs/sitemap.xml'
    types:
      - 'closed'

jobs:
  generate_sitemap:
    runs-on: ubuntu-latest

    steps:
      - name: 更新网站地图
        uses: DuckDuckStudio/Sitemap_Creator@1.0.9
        with:
          ...参数...
```

拉取请求合并（关闭）触发工作流 → 执行我们的 Action ↓
检测并移除已合并的相关 PR 的分支 → 关闭过时 PR → 创建新的网站地图^1 → 检查网站地图是否有变化 - 预期 → 没有变化，结束

^1 预期中此时网站地图不再发生变化，就不会再创建多余的 PR。
