### ISSUE TITLE
[Feat]: 自定义 PR 标题 / 提交消息

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Sitemap_Creator#8]
### 选择一个类别

新功能

### 对新功能/建议的描述

允许通过参数自定义 PR 标题 和 提交消息，并给出默认值。

### 为什么需要实现此功能

个性化

### 对于实施该功能的方法的建议

在参数中
```yml
inputs:
  pr_title:
    required: false
    description: 更新拉取请求的标题
    default: "[$(date +%Y%m%d%H%M%S)] 自动更新网站地图" # 使用 Bash 上的方式
  commit_message: # 或直接叫 message
    required: false
    description: 更新提交的消息
    default: "[$(date +%Y%m%d%H%M%S)] 自动更新网站地图" # 使用 Bash 上的方式
```

参数判断部分
```bash
# 更新方式: Commit
# 不得同时使用的参数
params=("LABELS" "AUTO_MERGE" "PR_TITLE")

# 遍历参数名称数组，检查冲突
for param_name in "${params[@]}"; do
  param_value="${!param_name}"
  if [[ -n "$param_value" ]]; then
    echo "[ERROR] 错误的参数传递"
    echo "[TIP] $param_name 参数不得与更新方式“提交”共存"
    exit 1
  fi
done
```

具体使用时
```bash
# 提交并推送 sitemap.xml
git add "$LOCATION"
git commit -m "$COMMIT_MESSAGE"
git config --global push.autoSetupRemote true
git push

# 拉取请求更新后续还要做的
if [[ "$UPDATE_WAY" == "PR" ]]; then
  # 创建拉取请求
  PR_URL=$(gh pr create --title "$PR_TITLE" \
                        --body "此拉取请求通过 [工作流](${WORKFLOW_URL}) 使用 [Sitemap Creator](https://github.com/DuckDuckStudio/Sitemap_Creator) 创建。" \
                        --base ${{ inputs.base_branch }} \
                        --head $BRANCH_NAME)
  echo "[INFO] 已创建拉取请求: $PR_URL"
```
> [!NOTE]
> `$COMMIT_MESSAGE` 和 `$PR_TITLE` 均来自环境变量，我不确定它们能否添加像时间这种会变化的参数。  
> 如果允许带参数添加，可能需要更多的安全处理。
