### ISSUE TITLE
[Feat]: 自定义更新提交撰写者

### ISSUE THREAD

**Issue by DuckDuckStudio** [DuckDuckStudio/Sitemap_Creator#9]
### 选择一个类别

新功能

### 对新功能/建议的描述

允许通过参数自定义更新提交的撰写者，并给出默认值（GitHub Action [bot]）。

### 为什么需要实现此功能

个性化

### 对于实施该功能的方法的建议

在参数中
```yml
inputs:
  author_name:
    required: false
    description: 更新提交的撰写者名
    default: "github-actions[bot]"
  author_email:
    required: false
    description: 更新提交的撰写者邮箱
    default: "41898282+github-actions[bot]@users.noreply.github.com"
```

> [!NOTE]
> 可能需要更多的安全处理。
